### ISSUE TITLE
 ATTENTION: 3rd Axis motor issue, 7 days past and no response

### ISSUE THREAD

**Issue by OPusG5** [AmberInside/Amber_AI_ROS2#7]
Hi, since I receive this robot, the 3rd axis motor isn't moving, I check the wire plugs, also plugged in the spare wire to try, and still not working, getting the same issue, unless you have any more suggestions, I might need a replacement motor sent to me.

**Comment by GHHofstetter** [comment]
A lot of us have been having issues with certain axis from time to time. My J2 has been acting up here and there. It is usually resolved after a clean bootup: 

1. All power off
2. Put the robot in the home position by manually moving all the joints so that it is vertical and turned on its base such that all joints with endstop brackets have those brackets aligned opposite each other. Support the robot so it doesn’t fall.
3. Power up the robot via the 48V PSU and by twisting the e-stop switch so it pops up.
4. Power up the UP2 board and log in.
5. Start the ROS2 environment.
6. Start the B1 application
7. Open the web page for the application.
8. Click the connection link.
9. Test motion controls to see if connection is good. If not, shut down UP2 box and remover power. Go back to (4).
10. Verify range and smoothness of motion with controls on Home page.
11. Press home button at bottom right of page and verify that robot returns to vertically aligned position.

Try this a couple times and if it still doesnt work, hop on our discord because we are together trying to figure this all out: https://discord.gg/wC5mYbEx

**Comment by AmberInside** [comment]
> Hi, since I receive this robot, the 3rd axis motor isn't moving, I check the wire plugs, also plugged in the spare wire to try, and still not working, getting the same issue, unless you have any more suggestions, I might need a replacement motor sent to me.

It's been transfered to our support team, they will help you figure it out.  please send us an email as before,  that will help us to know your order and your contact information.

**Comment by AmberInside** [comment]
> A lot of us have been having issues with certain axis from time to time. My J2 has been acting up here and there. It is usually resolved after a clean bootup:
> 
> 1. All power off
> 2. Put the robot in the home position by manually moving all the joints so that it is vertical and turned on its base such that all joints with endstop brackets have those brackets aligned opposite each other. Support the robot so it doesn’t fall.
> 3. Power up the robot via the 48V PSU and by twisting the e-stop switch so it pops up.
> 4. Power up the UP2 board and log in.
> 5. Start the ROS2 environment.
> 6. Start the B1 application
> 7. Open the web page for the application.
> 8. Click the connection link.
> 9. Test motion controls to see if connection is good. If not, shut down UP2 box and remover power. Go back to (4).
> 10. Verify range and smoothness of motion with controls on Home page.
> 11. Press home button at bottom right of page and verify that robot returns to vertically aligned position.
> 
> Try this a couple times and if it still doesnt work, hop on our discord because we are together trying to figure this all out: https://discord.gg/wC5mYbEx

The best way to launch B1, please see the latest updated wiki by the link below. 
It'll be updated in time once we got any userful response. 

https://github.com/AmberInside/Amber_AI_ROS2/wiki/Launch-AMBER-Robotics-Studio,-the-web-based-tool-for-AMBER-B1

**Comment by OPusG5** [comment]
> > Hi, since I receive this robot, the 3rd axis motor isn't moving, I check the wire plugs, also plugged in the spare wire to try, and still not working, getting the same issue, unless you have any more suggestions, I might need a replacement motor sent to me.
> 
> It's been transfered to our support team, they will help you figure it out. please send us an email as before, that will help us to know your order and your contact information.

opusg5@gmail.com

**Comment by OPusG5** [comment]
Hello, it's been one week since I posted my issue with the 3rd axis motor that's not working at all, I also sent an email to your company and haven't got any response, what's the status on this issue? my email address is opusg5@gmail.com

**Comment by AmberInside** [comment]
> Hi, since I receive this robot, the 3rd axis motor isn't moving, I check the wire plugs, also plugged in the spare wire to try, and still not working, getting the same issue, unless you have any more suggestions, I might need a replacement motor sent to me.

A email come to you, if not, leave a mesage here.

**Comment by OPusG5** [comment]
Thank you! replaced with a new motor and now everything works.
