### ISSUE TITLE
Firmware installation problem

### ISSUE THREAD

**Issue by apslowik** [AmberInside/Amber_AI_ROS2#8]
Hi,

I cannot install firmware, because the fw memory does not show. No matter whether I boot from the official Amber USB stick or I create my own bootable USB stick, the problem is always the same. This is the screen I end up with:

![IMG_7328](https://user-images.githubusercontent.com/27472998/154354053-09584370-1531-43ac-89cc-2efad386f514.jpg)

**Comment by GHHofstetter** [comment]
Step 1: You need to delete the top one. 

Step 2: Create a new partition of about 500 MB

step 3: SInce you only used 500 MB of the top one, there should still be like 28.5 Gb left to create a second partition.

Step 4: follow the steps from amber then on.

Basically there is already a partition there. You need to delete it and separate it. Hope on the discord if you need us to walk you through it: https://discord.gg/GRKUWb5B

**Comment by apslowik** [comment]
Thanks for prompt support. That worked for me, so installation went on, reported 100% complete, rebooted. Now PC is dead, blank screen, nothing. How to reboot from USB now? Is there a link to documentation for that motherboard available?

**Comment by apslowik** [comment]
Working for me know. Seems that something fails if boot partition is 512MB or larger. Keeping button pressed when connecting power allows for reinstallation :-)
